name: Weekly Tests

on:
  schedule:
    - cron: '0 3 * * 0' # Run every Sunday at 3 AM
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: pnpm setup
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        id: tests
        run: pnpm test

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_title = "Weekly test run failed";
            const issue_body = `The weekly test run failed on ${new Date().toUTCString()}.

            [View run details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue_title,
              body: issue_body
            });
